export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  KYC_PENDING = 'KYC_PENDING',
  DOCUMENTS_PENDING = 'DOCUMENTS_PENDING',
  UNDER_AUTOMATED_REVIEW = 'UNDER_AUTOMATED_REVIEW',
  UNDER_ADMIN_REVIEW = 'UNDER_ADMIN_REVIEW',
  MORE_INFORMATION_REQUIRED = 'MORE_INFORMATION_REQUIRED',
  APPROVED = 'APPROVED',
  APPROVED_WITH_EXCEPTION = 'APPROVED_WITH_EXCEPTION',
  REJECTED = 'REJECTED',
  CONTRACT_PENDING = 'CONTRACT_PENDING',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  DISBURSEMENT_PENDING = 'DISBURSEMENT_PENDING',
  DISBURSED = 'DISBURSED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}
export const TERMINAL_STATUSES = new Set<ApplicationStatus>([
  ApplicationStatus.REJECTED,
  ApplicationStatus.CLOSED,
  ApplicationStatus.CANCELLED,
]);
